In [1]:
import timeit
from itertools import combinations
from collections import Counter
from multiprocessing import Pool #  Process pool

In [2]:
import numpy as np
import pandas as pd

In [3]:
from Card import Card
from Hand import Hand
from Deck import Deck
from Utils import *
from Exception import *

In [4]:
%load_ext autoreload
%autoreload 2

In [5]:
# Initialize a Card Deck
deck = Deck()
deck.shuffle()

In [6]:
p1 = Hand(deck.deck[0:5])

[(4, 1) (10, 3) (10, 4) (14, 1) (14, 3)]
[(4, 1) (10, 3) (10, 4) (14, 1) (14, 3)]


In [7]:
p2 = Hand(deck.deck[2:7])

[(2, 3) (4, 1) (10, 4) (11, 2) (14, 3)]
[(2, 3) (4, 1) (10, 4) (11, 2) (14, 3)]


In [100]:
### 2 cards left, runtime 4s
### 3 cards left, runtime 58s
### 4 cards left, runtime ??s (find_all_combinations)
### 5 cards left, runtime ??s (find all combinations)

In [131]:
total = deck.deck
selected = 5
combos = np.empty(num_combinations(len(total), selected), dtype=object)
for idx, hand in enumerate(combinations(total, selected)):
#     temp = np.empty(len(hand), dtype=object)
#     temp[:] = hand
    temp = Hand(hand)
    combos[idx] = temp

In [136]:
pd.Series([x.value for x in combos]).value_counts()

1     1302540
2     1098240
3      123552
4       54912
5       10200
6        5108
7        3744
8         624
9          36
10          4
dtype: int64

In [137]:
len(pd.Series([x.value for x in combos]).unique())

7462

In [145]:
pd.Series([x.value for x in combos]).value_counts().value_counts()

384     2860
4       1443
1020    1287
144      858
64       858
24       156
dtype: int64

In [ ]:
pd.Series([(x.rank, x.value) for x in combos]).value_counts()

In [ ]:
pd.Series([x.rank[0] for x in combos]).

In [108]:
# np.argmin([x.value for x in combos])

In [109]:
# combos[760050].rank

In [132]:
# np.argmin([x.value for x in combos])

In [118]:
2*(16**5)

2097152

In [116]:
combos[85].rank

array([ 2, 12,  5,  3,  2])

In [9]:
p1_vec = np.repeat(p1, num_combinations(len(total), selected))

In [10]:
p2_vec = np.repeat(p2, num_combinations(len(total), selected))

In [104]:
start = timeit.default_timer()
p1_combos = Hand.concatenate(p1_vec, combos)
end = timeit.default_timer()
print(end - start)

0.0639523999998346


In [105]:
start = timeit.default_timer()
p1_combos = p1_vec + combos
end = timeit.default_timer()
print(end - start)

0.044035799999619485


In [106]:
p2_combos = Hand.concatenate(p2_vec, combos)

In [107]:
time_ = []
for i in range(100):
    start = timeit.default_timer()
    res = Hand(max(list(map(Hand, combinations(p1_combos[0].hand_candidates, 5)))).hand_candidates)
    end = timeit.default_timer()
    time_ += [end - start]
np.sum(time_)

0.45899970000164103

In [108]:
time_ = []
for i in range(1000):
    start = timeit.default_timer()
    res = Hand(sorted(list(map(Hand, combinations(p1_combos[0].hand_candidates, 5))))[-1].hand_candidates)
    end = timeit.default_timer()
    time_ += [end - start]
np.sum(time_)

5.01043280000431

In [109]:
# start = timeit.default_timer()
# p1_select = Hand.find_max(p1_combos)
# end = timeit.default_timer()
# print(end - start)

In [110]:
# start = timeit.default_timer()
# p2_select = Hand.find_max(p2_combos)
# end = timeit.default_timer()
# print(end - start)

In [111]:
res = Hand.compare(p1_select, p2_select)

In [112]:
Counter(res)

Counter({1: 10292, -1: 2952})

In [113]:
str(p1), str(p2)

("Three of a Kind ['8c', '9c', '9d', '9h', 'Qs']",
 "High Card ['3s', '4d', '8c', '9h', 'Qs']")

In [101]:
# [str(x) for x in sorted(p1_select)]

In [100]:
# [str(x) for x in sorted(p2_select)]

In [116]:
p2_combos.shape

(946,)

In [117]:
### Ideas for frequency calculation

In [118]:
rank_dict =  {10: 'Royal Flush',
    9: 'Straight Flush',
    8: 'Four of A Kind',    
    7: 'Full House',   
    6: 'Flush',
    5: 'Straight',
    4: 'Three of a Kind',   
    3: 'Two Pair',          
    2: 'One Pair',          
    1: 'High Card'}

In [119]:
c = Counter([x.rank for x in p1_select])

In [120]:
[(rank_dict[i], c[i] / len(p1_select) * 100.0) for i in c]

[('Two Pair', 32.43733011174872),
 ('Full House', 2.4841437632135306),
 ('One Pair', 56.89368770764119),
 ('Three of a Kind', 5.48172757475083),
 ('Straight', 1.4497130776200544),
 ('Four of A Kind', 0.007550588945937783),
 ('Flush', 1.215644820295983),
 ('Straight Flush', 0.030202355783751134)]

In [121]:
c = Counter([x.rank for x in p2_select])

In [122]:
[(rank_dict[i], c[i] / len(p2_select) * 100.0) for i in c]

[('Two Pair', 13.205980066445184),
 ('One Pair', 49.10903050437934),
 ('Three of a Kind', 2.536997885835095),
 ('High Card', 31.357595892479612),
 ('Straight', 2.0462096043491393),
 ('Flush', 1.2458471760797343),
 ('Full House', 0.47568710359408034),
 ('Four of A Kind', 0.02265176683781335)]

In [151]:
total = deck.deck[:48]
selected = 4
combos = np.empty(num_combinations(len(total), selected), dtype=object)
for idx, hand in enumerate(combinations(total, selected)):
    temp = np.empty(len(hand), dtype=object)
    temp[:] = hand
    combos[idx] = temp

In [152]:
p3_vec = np.repeat(Hand([deck.deck[50]]), repeats=len(combos))
# p3_vec = p3_vec + combos

In [102]:
# p3_res = p3_vec + combos

In [154]:
c = Counter([x.rank for x in p3_res])

In [155]:
[(rank_dict[i], c[i] / len(p3_res) * 100.0) for i in c]

[('Three of a Kind', 1.4055915304758968),
 ('One Pair', 39.99383287079865),
 ('Two Pair', 3.8775824853530683),
 ('Full House', 0.0770891150169596),
 ('Four of A Kind', 0.005139274334463974),
 ('High Card', 54.157159009147904),
 ('Flush', 0.2533662246890739),
 ('Straight', 0.22921163531709324),
 ('Royal Flush', 0.0005139274334463973),
 ('Straight Flush', 0.0005139274334463973)]

In [11]:
def concat(hand_1, hand_2):
    Hand.concatenate(hand_1, hand_2)

In [14]:
p = Pool(8)
# p.map(concat, p3_res[1:10])

In [13]:
p.map(concat, )

In [ ]:
def f(x):
    return x*x

p = Pool(5)
print(p.map(f, [1, 2, 3]))

In [28]:
class C(np.ndarray):
    def __new__(cls, *args, **kwargs):
        print('In __new__ with class %s' % cls)
        return np.asarray(input_array).view(cls)
#         return super(C, cls).__new__(cls, *args, **kwargs)

    def __init__(self, *args, **kwargs):
        # in practice you probably will not need or want an __init__
        # method for your subclass
        print('In __init__ with class %s' % self.__class__)

    def __array_finalize__(self, obj):
        print('In array_finalize:')
        print('   self type is %s' % type(self))
        print('   obj type is %s' % type(obj))

In [30]:
C(input_array=[[2,3], [4,5], [6,7], [8,9], [4,3]])

In __new__ with class <class '__main__.C'>


NameError: name 'input_array' is not defined

In [57]:
np.append(np.array([[2,3],[4,5], [6,7]]), np.array([[2,3],[4,5]]), axis=0)

array([[2, 3],
       [4, 5],
       [6, 7],
       [2, 3],
       [4, 5]])

In [ ]:
np.array([[2,3],[4,5], [6,7]])

In [60]:
combos

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
total = deck.deck[8:22]
selected = 5
combos = np.empty(shape=(num_combinations(len(total), selected), selected, 2))
for idx, item in enumerate(combinations(total, selected)):
    combos[idx] = np.array(item, dtype=int)
#     temp = np.empty(len(hand), dtype=object)
#     temp[:] = hand
#     combos[idx] = temp

In [ ]:
    ### Helper functions to get hand values
    def _hand_values(self, hand):
        return sorted([card[0] for card in hand])

    def _hand_suits(self, hand):
        return sorted([card[1] for card in hand])

    ### Convenient Quick Check
    """
    Checks if all five cards are of the same suit
    True: 5 cards are of the same suit
    False: 5 cards are of different suit
    """

    def suit_check(self, hand):
        if len(np.unique(self._hand_suits(hand))) == 1:
            return True
        return False

    """
    Checks if the five cards form a straight
    True: 5 cards form a straight
    False: 5 cards do not form a straight
    """

    def straight_check(self, hand):
        hand_values = self._hand_values(hand)
        # print(hand_values)
        # print(type(hand_values))
        # print(np.arange(hand_values[0], hand_values[0] + 5, 1))
        # print(hand_values == np.arange(hand_values[0], hand_values[-1] + 1, 1))
        if hand_values == list(np.arange(hand_values[0], hand_values[0] + 5, 1)) or (
                hand_values == [2,3,4,5,14]):
            return True
        return False

    """
    Assigns the rank of the hand
    """

    def assign_rank(self, hand):

        suit_check = self.suit_check(hand)
        straight_check = self.straight_check(hand)
        hand_values = self._hand_values(hand)
        
        if hand_values == [2,3,4,5,14]:
            hand_values = [1,2,3,4,5]
        ### We could use straight check and suit check to quickly determine certain card types
        if suit_check and straight_check and hand_values[0] == 10:
            return np.array([10] + hand_values[::-1])
        elif suit_check and straight_check:
            return np.array([9] + hand_values[::-1])
        elif suit_check:
            return np.array([6] + hand_values[::-1])
        elif straight_check:
            return np.array([5] + hand_values[::-1])

        ### Assign all other categories
        val, count = np.unique(hand_values, return_counts=True)
        return np.array([self._rank_dict((max(count), min(count), len(count)))] + list(val[count.argsort()])[::-1])
    
    def assign_value(self, hand_array):
        ### Algorithm to assign a unique value to the hand
        return int(np.sum(np.exp2(np.arange(20, 20 - len(hand_array) * 4, -4)) * hand_array))

    def _rank_dict(self, max_min_len):
        rank_params_dict = {(4, 1, 2): 8, (3, 2, 2): 7, (3, 1, 3): 4, (2, 1, 3): 3, (2, 1, 4): 2, (1, 1, 5): 1}
        return rank_params_dict[max_min_len]


In [141]:
_hand_values(res[7:10], 0)

array([[12,  9,  3,  5,  3],
       [12,  9,  3, 10, 10],
       [12,  9,  3, 10,  7]])

In [ ]:
val, count = np.unique(hand_values, return_counts=True)
#         print(val, count)
        return np.array([self._rank_dict((max(count), min(count), len(count)))] + list(val[count.argsort()])[::-1])
    
    def assign_value(self, hand_array):
#         print(np.arange(20, 20 - len(hand_array) * 4, -4))
#         print(hand_array)
        return int(np.sum(np.exp2(np.arange(20, 20 - len(hand_array) * 4, -4)) * hand_array))

    def _rank_dict(self, max_min_len):
        rank_params_dict = {(4, 1, 2): 8, (3, 2, 2): 7, (3, 1, 3): 4, (2, 1, 3): 3, (2, 1, 4): 2, (1, 1, 5): 1}
        return rank_params_dict[max_min_len]


In [152]:
np.unique(_hand_values(res[7], axis=0), return_counts=True)

(array([ 3,  5,  9, 12]), array([2, 1, 1, 1], dtype=int64))

In [149]:
def _hand_values(hand, axis):
    return hand[:, axis]

def _hand_suits(hand, axis):
    return hand[:, axis]

In [110]:
_hand_values(res[1:3])

array([[12,  9,  3,  5, 10, 10,  5],
       [12,  9,  3,  5, 10, 10,  9]])

In [111]:
_hand_suits(res[1:3])

array([[3, 3, 1, 1, 2, 1, 3],
       [3, 3, 1, 1, 2, 1, 1]])

In [123]:
np.apply_over_axes(_hand_values, res[1:3], axes=[0])

array([[[12,  9,  3,  5, 10],
        [12,  9,  3,  5,  7]]])

In [32]:
np.apply_along_axis(np.sum, 2, combos[1:3])

array([[15., 12.,  4.,  6., 11.],
       [15., 12.,  4.,  6., 11.]])

In [122]:
total = deck.deck[8:20]
selected = 5
combos = np.empty(shape=(num_combinations(len(total), selected), selected, 2), dtype=int)
res = np.array(list(combinations(total, selected)))
#     temp = np.empty(len(hand), dtype=object)
#     temp[:] = hand
#     combos[idx] = temp

In [130]:
import numpy as np
from itertools import combinations
from Exception import *



class Hand:
    """
    A class that identifies the Hand Type

    10: Royal Flush
    9: Straight Flush
    8: Four of A Kind    4, 1, 2
    7. Full House        3, 2, 2
    6: Flush
    5: Straight
    4: Three of a Kind   3, 1, 3
    3: Two Pair          2, 1, 3
    2: One Pair          2, 1, 4
    1: High Card         1, 1, 5
    """

    def __init__(self, cards) -> None:
        # if len(cards) > 5:
        self.hand_candidates = self.create_hand(cards)

        if len(cards) <= 5:
            self.hand = self.create_hand(cards, sort=True)
#         self._valid_hand(self.hand)

            if len(self.hand) == 5:
                self.rank = self.assign_rank(self.hand)
                self.value = self.assign_value(self.rank)
            else:
                self.rank = 0
                self.value = 0

    def create_hand(self, cards, sort=False):
        # if len(cards) > 5:
        #     return max(list(map(Hand, combinations(cards, 5)))).hand

        cardlist = np.empty((len(cards),), dtype=object)
        if sort:
            cardlist[:] = sorted(cards)
        else:
            cardlist[:] = cards
        return cardlist

    ### Buggy Don't Need It
    #     def remove_card(self, card):
    #         self.hand = self.hand[self.hand != card]
    @staticmethod
    @np.vectorize
    def concatenate(hand_1, hand_2):
        if isinstance(hand_1, Hand) and isinstance(hand_2, Hand):
            return Hand(np.append(hand_1.hand_candidates, hand_2.hand_candidates))
        elif isinstance(hand_1, Hand):
            return Hand(np.append(hand_1.hand_candidates, hand_2))
        elif isinstance(hand_2, Hand):
                # return Hand(max(list(map(Hand, combinations(np.append(hand_1, hand_2.hand), 5)))).hand)
            return Hand(np.append(hand_1, hand_2.hand_candidates))
                # return Hand(max(list(map(Hand, combinations(np.append(hand_1.hand, hand_2.hand), 5)))).hand)
        return Hand(np.append(hand_1, hand_2))

    @staticmethod
    @np.vectorize
    def find_max(hand):
        if isinstance(hand, Hand):
            if len(hand.hand_candidates) > 5:
                return Hand(max(list(map(Hand, combinations(hand.hand_candidates, 5)))).hand_candidates)
            return hand
        else:
            if len(hand.hand_candidates) > 5:
                return Hand(max(list(map(Hand, combinations(hand, 5)))).hand_candidates)
            return Hand(hand)


    def __add__(self, other):
        if isinstance(other, Hand):
            return Hand(np.append(self.hand_candidates, other.hand_candidates))
        else:
            print(self.hand_candidates)
            return Hand(np.append(self.hand_candidates, other))

    def __radd__(self, other):
        if isinstance(other, Hand):
            return Hand(np.append(self.hand_candidates, other.hand_candidates))
        else:
            return Hand(np.append(self.hand_candidates, other))

    def _valid_hand(self, hand):
#         if len(hand) > 5:
#             raise HandException("Hand Size has Exceeded the Limit of 5")
#         tupled_card = [tuple(card) for card in hand]
#         if len(tupled_card) != len(list(set(tupled_card))):
#             raise HandException("Duplicate Cards Found in Hand")
        pass

    ### Helper functions to get hand values
    def _hand_values(self, hand):
        return sorted([card[0] for card in hand])

    def _hand_suits(self, hand):
        return sorted([card[1] for card in hand])

    ### Convenient Quick Check
    """
    Checks if all five cards are of the same suit
    True: 5 cards are of the same suit
    False: 5 cards are of different suit
    """

    def suit_check(self, hand):
        if len(np.unique(self._hand_suits(hand))) == 1:
            return True
        return False

    """
    Checks if the five cards form a straight
    True: 5 cards form a straight
    False: 5 cards do not form a straight
    """

    def straight_check(self, hand):
        hand_values = self._hand_values(hand)
        # print(hand_values)
        # print(type(hand_values))
        # print(np.arange(hand_values[0], hand_values[0] + 5, 1))
        # print(hand_values == np.arange(hand_values[0], hand_values[-1] + 1, 1))
        if hand_values == list(np.arange(hand_values[0], hand_values[0] + 5, 1)) or (
                hand_values == [2,3,4,5,14]):
            return True
        return False

    """
    Assigns the rank of the hand
    """

    def assign_rank(self, hand):

        suit_check = self.suit_check(hand)
        straight_check = self.straight_check(hand)
        hand_values = self._hand_values(hand)
        
        if hand_values == [2,3,4,5,14]:
            hand_values = [1,2,3,4,5]
        ### We could use straight check and suit check to quickly determine certain card types
        if suit_check and straight_check and hand_values[0] == 10:
            return np.array([10] + hand_values[::-1])
        elif suit_check and straight_check:
            return np.array([9] + hand_values[::-1])
        elif suit_check:
            return np.array([6] + hand_values[::-1])
        elif straight_check:
            return np.array([5] + hand_values[::-1])

        ### Assign all other categories
        val, count = np.unique(hand_values, return_counts=True)
#         print(val, count)
        return np.array([self._rank_dict((max(count), min(count), len(count)))] + list(val[count.argsort()])[::-1])
    
    def assign_value(self, hand_array):
        return int(np.sum(np.exp2(np.arange(20, 20 - len(hand_array) * 4, -4)) * hand_array))

    def _rank_dict(self, max_min_len):
        rank_params_dict = {(4, 1, 2): 8, (3, 2, 2): 7, (3, 1, 3): 4, (2, 1, 3): 3, (2, 1, 4): 2, (1, 1, 5): 1}
        return rank_params_dict[max_min_len]


    ### Overwriting Comparison Operators
    def __eq__(self, other) -> bool:
        if isinstance(other, Hand):
            if self.rank != other.rank:
                return False
            elif Hand.in_rank_comparison(self.in_rank_values, other.in_rank_values) == 0:
                return True
            return False
        return False

    def __gt__(self, other) -> bool:
        if isinstance(other, Hand):
            if self.rank > other.rank:
                return True
            elif self.rank < other.rank:
                return False
            elif Hand.in_rank_comparison(self.in_rank_values, other.in_rank_values) == 1:
                return True
            return False
        return False

    def __lt__(self, other) -> bool:
        if isinstance(other, Hand):
#             print(self.hand, other.hand, 'self other hand')
#             print(self.in_rank_values, other.in_rank_values, 'self other in rank')
#             print(self.rank, other.rank, 'self other rank')
            if self.rank < other.rank:
                return True
            elif self.rank > other.rank:
                return False
            elif Hand.in_rank_comparison(self.in_rank_values, other.in_rank_values) == -1:
                return True
            return False
        return False

    def __ge__(self, other) -> bool:
        if isinstance(other, Hand):
            if self.rank > other.rank:
                return True
            elif self.rank < other.rank:
                return False
            elif Hand.in_rank_comparison(self.in_rank_values, other.in_rank_values) in [0, 1]:
                return True
            return False
        return False

    def __le__(self, other) -> bool:
        if isinstance(other, Hand):
            if self.rank < other.rank:
                return True
            elif self.rank > other.rank:
                return False
            elif Hand.in_rank_comparison(self.in_rank_values, other.in_rank_values) in [0, -1]:
                return True
            return False
        return False

    def __ne__(self, other) -> bool:
        if isinstance(other, Hand):
            if self.rank != other.rank:
                return False
            elif Hand.in_rank_comparison(self.in_rank_values, other.in_rank_values) == 0:
                return True
            return False
        return False

    @staticmethod
    def in_rank_comparison(hand_value_1, hand_value_2):

        if hand_value_1 == [2, 3, 4, 5, 14]:
            hand_value_1 = [1, 2, 3, 4, 5]
        if hand_value_2 == [2, 3, 4, 5, 14]:
            hand_value_2 = [1, 2, 3, 4, 5]

        if hand_value_1 == hand_value_2:
            return 0

        for i in range(-1, -len(hand_value_1) - 1, -1):
            if hand_value_1[i] > hand_value_2[i]:
                return 1
            elif hand_value_1[i] < hand_value_2[i]:
                return -1


    @staticmethod
    @np.vectorize
    def compare(hand_1, hand_2) -> int:
        if hand_1.rank > hand_2.rank:
            return 1
        elif hand_1.rank < hand_2.rank:
            return -1
        return Hand.in_rank_comparison(hand_1.in_rank_values, hand_2.in_rank_values)

    @staticmethod
    @np.vectorize
    def multi_compare() -> int:
        pass



    ### Overwriting String Operation
    def __str__(self) -> str:
        category_strings = {10: 'Royal Flush', 9: 'Straight Flush', 8: 'Four of a Kind',
                            7: 'Full House', 6: 'Flush', 5: 'Straight', 4: 'Three of a Kind', 3: 'Two Pairs',
                            2: 'One Pair', 1: 'High Card'}
        if len(self.hand_candidates) == 5:
            return category_strings.get(self.rank) + " " + str([card.__str__() for card in self.hand_candidates])
        return str([card.__str__() for card in self.hand_candidates])

    #     def assign_table(self):
    #         temp = dict()
    #         for card in self.cardlist:
    #             if card[0] in temp.keys():
    #                 temp[card[0]] += 1
    #             else:
    #                 temp[card[0]] = 1
    #         temp = dict(sorted(temp.items(), key=lambda x: x[1], reverse=True))

    #         result = []
    #         for value in list(sorted(set(temp.values()), reverse=True)):
    #             l1 = sorted([k for k, v in temp.items() if v == value], reverse=True)
    #             # print(l1)
    #             for i in range(len(l1)):
    #                 for j in range(value):
    #                     result.append(l1[i])
    #         return result



In [56]:
np.array([0,np.array([2,34,5])])

array([0, array([ 2, 34,  5])], dtype=object)

In [58]:
[3] + np.array([2,3,4])

array([5, 6, 7])

In [123]:
np.arange(20, 20 - 3* 4 - 1,-4)

array([20, 16, 12,  8])